name: kkbox_openapi
description: KKBOX's Open API provides various data from KKBOX's rich music archive. It helps you to access data about KKBOX's song tracks, albums, artist playlist and so on.
version: 2.2.0+4
homepage: https://github.com/KKBOX/OpenAPI-Dart
author: zonble <zonble@gmail.com>

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  http: ^0.12.0+3
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.4
  test_coverage: ^0.4.0

