name: kkbox_openapi
description: A starting point for Dart libraries or applications.
version: 2.1.0+6
homepage: https://xddd.kkbox.io/kkbox_openapi_dart
author: zonble <zonble@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  test_coverage: ^0.2.0
